#!/usr/bin/env python

import os
from adytum.app.pymon.api import constants

app = os.path.join(constants.INSTALL_DIR, constants.PYMON_APP)
args = (constants.TWISTD, '-noy', app)
cmd = (constants.TWISTD, args)

#exec $TWIST -noy $SERVER
os.execv(*cmd)
